# Generated by Django 3.1.2 on 2021-07-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sacco_manager', '0002_auto_20210704_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.route')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.sacco')),
                ('stagecontroller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.stagecontroller')),
            ],
            options={
                'db_table': 'ride_fare',
            },
        ),
    ]
