# Generated by Django 3.1.2 on 2021-07-03 12:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sacco_driver',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('sacco_reg_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sacco_name', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sacco',
            },
        ),
        migrations.CreateModel(
            name='SaccoRegistrationRequests',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('sacco_reg_no', models.CharField(max_length=50)),
                ('sacco_name', models.CharField(max_length=100)),
                ('date_reguested', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(default='in_progress', max_length=15)),
            ],
            options={
                'db_table': 'sacco_requests',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('v_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='sacco_manager.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='sacco_manager.route')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacco', to='sacco_manager.sacco')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_booking', models.DateTimeField(auto_now_add=True)),
                ('final_booking', models.DateTimeField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.vehicle')),
            ],
            options={
                'db_table': 'vstatus',
            },
        ),
        migrations.CreateModel(
            name='VehicleBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.vehicle')),
            ],
            options={
                'db_table': 'vbookings',
            },
        ),
        migrations.CreateModel(
            name='VControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('v_availability_by_driver', models.BooleanField(default=False)),
                ('controller_confirmation_status', models.BooleanField(default=False)),
                ('time_available_by_driver', models.DateTimeField(default=datetime.datetime(2021, 7, 3, 12, 15, 30, 717197))),
                ('time_of_confirmation_by_controller', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcontrol', to='sacco_manager.vehicle')),
            ],
            options={
                'db_table': 'vehiclecontrol',
            },
        ),
        migrations.CreateModel(
            name='StageController',
            fields=[
                ('id_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_stagecontroller', to='sacco_manager.sacco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stagecontroller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stage_controller',
            },
        ),
        migrations.CreateModel(
            name='SaccoManager',
            fields=[
                ('id_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sacco_manager',
            },
        ),
        migrations.AddField(
            model_name='sacco',
            name='sacco_manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sacco', to='sacco_manager.saccomanager'),
        ),
        migrations.AddField(
            model_name='route',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.sacco'),
        ),
        migrations.CreateModel(
            name='FareTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transacted', models.DateTimeField(auto_now_add=True)),
                ('departure_town', models.CharField(default='XYZ', max_length=50)),
                ('destination_town', models.CharField(default='ZYX', max_length=50)),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.vehicle')),
            ],
            options={
                'db_table': 'fareTransactions',
            },
        ),
    ]
