# Generated by Django 3.1.2 on 2021-07-04 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcontrol',
            name='time_available_by_driver',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 9, 6, 37, 219756)),
        ),
    ]
