# Generated by Django 3.1.2 on 2021-07-15 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_manager', '0003_auto_20210713_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcontrol',
            name='time_available_by_driver',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 14, 46, 49, 33553)),
        ),
    ]
