# Generated by Django 3.1.2 on 2021-07-18 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_manager', '0004_auto_20210715_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebookings',
            name='booking_code',
            field=models.PositiveIntegerField(default=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vcontrol',
            name='time_available_by_driver',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 9, 2, 41, 778140)),
        ),
    ]
