# Generated by Django 3.1.2 on 2021-07-18 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_manager', '0005_auto_20210718_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebookings',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vcontrol',
            name='time_available_by_driver',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 9, 35, 1, 289872)),
        ),
    ]
