# Generated by Django 3.1.2 on 2021-07-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_manager', '0004_auto_20210715_1446'),
        ('mat360admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(max_length=10, unique=True)),
                ('transaction_time', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_shortcode', models.CharField(max_length=6)),
                ('invoice_number', models.CharField(blank=True, max_length=5, null=True)),
                ('msisdn', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('booking_code', models.PositiveIntegerField()),
                ('bill_refnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_manager.vehicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ride_payments',
            },
        ),
    ]
